### ISSUE TITLE
Landslide Layers

### ISSUE THREAD

**Issue by milafrerichs** [GFDRR/recovery_dashboard#48]
Would you like to combine the landslides layers?
We currently have 4 different landslides layers. We could combine them locally and display as one?
I'm asking because you only put one metadata description to the landslides layer:

> 1. Landslide inventory interpreted from satellite images. 

@ks2693 @avalenzuela00

**Comment by ks2693** [comment]
let's deal with the metadata later. I really need to be able to show the data. If you are able to combine the lines and points and polygons into one layer, then please show them as one layer. Can you do this?
