### ISSUE TITLE
Sub layer switcher not working

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/recovery_dashboard#54]
Not sure if I don't understand how to use or if it is not working fully but when I toggle between avg and number, the display doesn't change
![0290a4c7-95ae-44d2-97fb-d8a883407f8a](https://cloud.githubusercontent.com/assets/1036189/7842030/43091da2-04a9-11e5-9ad0-64c7c0bfc2cb.png)

**Comment by milafrerichs** [comment]
Yes it is not really working because it was used for switching the style of GeoJSON Layers but since the poverty layer is now a WMS Layer it is no longer working.
But we're changing the poverty layer to only show the avg number. will close this one.
